### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by paulo-raca** [ScienceStacks/jupyter_scisheets_widget#2]
Hello,
Thanks for this project, it seems _exactly_ like what I need.

Unfortunately, I haven't been able to set it up on my Jupyter server.
I've been at it for a couple of hours without success... Some help would be greatly appreciated :)

Specifically, `jupyter_scisheets_widget/static/` doesn't seem to exist during the build. As far as I can tell, npm have generated them it from the files in `js/lib`, but that doesn't happen. `python setup.py build` fails with this message:

> missing files: ['/home/jovyan/jupyter_scisheets_widget/jupyter_scisheets_widget/static/extension.js', '/home/jovyan/jupyter_scisheets_widget/jupyter_scisheets_widget/static/index.js']

You can check the complete error message in https://pastebin.com/nNugVXj2

Thanks a lot

**Comment by paulo-raca** [comment]
I've tried copying the files from `js/lib` into `jupyter_scisheets_widget/static/`.
While I managed to finish the compilation with that trick, it doesn't really work on the browser

**Comment by clarka34** [comment]
Hi Paulo! Did you follow the installation steps in the README by chance? I tried to reproduce your error, but I was not able to. 

Do you still get the error if you run the following?
conda create -n scisheets-widget-env python=2.7 notebook numpy pandas nb_conda
source activate scisheets-widget-env
conda install -c conda-forge ipywidgets nodejs
git clone https://github.com/ScienceStacks/jupyter_scisheets_widget.git
cd jupyter_scisheets_widget
python setup.py build
pip install -e .
jupyter nbextension install --py --symlink --sys-prefix jupyter_scisheets_widget
jupyter nbextension enable --py --sys-prefix jupyter_scisheets_widget

**Comment by paulo-raca** [comment]
Thanks for looking into it, @clarka34, it's much appreciated.

Yes, I followed the instructions on the README -- Until the `python setup.py build` anyway.

I've tried creating a conda environment as you said, but it crashes with the same problem :man_shrugging:

**Comment by clarka34** [comment]
@paulo-raca what os are you using? I have tested it on multiple mac/linux machines but never on a windows machine.

**Comment by paulo-raca** [comment]
I am doing it all on a docker image based on [jupyter/datascience-notebook](https://hub.docker.com/r/jupyter/datascience-notebook/) (Which is based on ubuntu:xenial).

**Comment by paulo-raca** [comment]
And as I prepared a simplified Dockerfile for attach here, everything started working.

Turns out that I was running the commands as root, which seems to break everything. 

![facepalm](https://user-images.githubusercontent.com/1072660/39324931-438104f6-4967-11e8-97f3-c00bed88d20f.jpg)

I'm sorry for the stupid issue, and thanks a ton for the help, @clarka34

**Comment by clarka34** [comment]
Glad you got it to work @paulo-raca!
